{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeops.serviceAccountName" . }}
  labels:
{{ include "kubeops.labels" . | nindent 4 }}
{{- end -}}
