name: Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - id: repolower
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - id: userlower
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository_owner }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.PUSH_SECRET }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ghcr.io/${{ steps.userlower.outputs.lowercase }}/${{ steps.repolower.outputs.lowercase }}:latest
